name: example
description: Example Flutter project demonstrating many_lints.
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  

dependency_overrides:
  analyzer: ^10.1.0
  meta: ^1.18.1