name: my_lints
description: "description: Custom lint rules using the Dart 3.10 analyzer plugin API."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.7

dependencies:
  analysis_server_plugin: ^0.3.0
  analyzer_plugin: ^0.13.0
  analyzer: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
